# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-22 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('detailid', models.IntegerField()),
            ],
        ),
    ]
