# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-06 02:13
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='n_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
