# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-06 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190306_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=100)),
                ('b_time', models.DateTimeField(auto_now=True)),
                ('b_content', models.TextField()),
            ],
        ),
    ]
