# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default='atom.png', max_length=40),
        ),
    ]
