# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_test',
            field=models.IntegerField(null=True),
        ),
    ]
