# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0002_student_s_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_math',
            field=models.IntegerField(default=0),
        ),
    ]
