# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0003_auto_20190226_0813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
