# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_score',
            field=models.IntegerField(default=0),
        ),
    ]
