# Generated by Django 2.0.7 on 2019-05-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusertoken',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
