# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
                ('s_score', models.IntegerField(null=True)),
                ('s_weight', models.FloatField(null=True)),
                ('s_height', models.DecimalField(decimal_places=1, max_digits=6)),
                ('s_detail', models.TextField(default='')),
                ('s_delete', models.BooleanField(default=False)),
                ('s_create', models.DateTimeField(auto_now_add=True)),
                ('s_change', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
