# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190227_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=40)),
                ('g_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='g_collection',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
